### ISSUE TITLE
Refactor Test Harness

### ISSUE THREAD

**Issue by jvc26** [pyroven/django-pyroven#14]
Tests currently are reasonably inflexible, and the runtests is fairly inelegant merging settings and tests.

I propose:

1. Clean implementation with settings and tests in separate package. As illustrated [here](https://docs.djangoproject.com/en/1.7/topics/testing/advanced/#using-the-django-test-runner-to-test-reusable-applications)
2. Use Tox to manage dependency/version matrices
3. Ensure we support both Django 1.7 and 1.6

**Comment by doismellburning** [comment]
s/package/module/?

**Comment by jvc26** [comment]
module, was what I meant.

**Comment by jvc26** [comment]
Consider most of this implemented in recent merge. 1.7 can be confirmed with issue pyroven/django-pyroven#17
