### ISSUE TITLE
Trove classifiers

### ISSUE THREAD

**Issue by jvc26** [pyroven/django-pyroven#30]
This may appear a little controversial (not sure if they are absent by choice/preference) but might we consider trove classifiers for the ```setup.py```? For example:

      classifiers=[
            'Environment :: Web Environment',
            'Framework :: Django',
            'Operating System :: OS Independent',
            'Intended Audience :: Developers',
            'License :: OSI Approved :: MIT License',
            'Programming Language :: Python',
            'Programming Language :: Python :: 2.6',
            'Programming Language :: Python :: 2.7',
            'Topic :: Internet :: WWW/HTTP',
      ],

**Comment by doismellburning** [comment]
Rather than the issue/PR dupe, lets just do this in the PR?
